// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.2.0.0
//      SpecFlow Generator Version:2.2.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace TestesIntegradosApi.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class RealizarRequisicaoAApiFeature : Xunit.IClassFixture<RealizarRequisicaoAApiFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "SpecFlowFeature1.feature"
#line hidden
        
        public RealizarRequisicaoAApiFeature(RealizarRequisicaoAApiFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Realizar requisição a api", "\t\t\t\tinformado o valor inicial e a quantidade de meses e\r\n\t\t\t\tobter o resultado do" +
                    " cálculo do juros", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.ScenarioTearDown();
        }
        
        [Xunit.FactAttribute(DisplayName="Requisição a api Cálculo de juros")]
        [Xunit.TraitAttribute("FeatureTitle", "Realizar requisição a api")]
        [Xunit.TraitAttribute("Description", "Requisição a api Cálculo de juros")]
        public virtual void RequisicaoAApiCalculoDeJuros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Requisição a api Cálculo de juros", ((string[])(null)));
#line 7
this.ScenarioSetup(scenarioInfo);
#line 8
 testRunner.Given("que realizo a requisição a api", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "quantidadeInicial",
                        "mes"});
            table1.AddRow(new string[] {
                        "100",
                        "5"});
#line 9
 testRunner.And("informo a quantidade inicial e a quantidade de meses", ((string)(null)), table1, "E ");
#line 12
 testRunner.Then("recebo o juros calculado", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [Xunit.FactAttribute(DisplayName="erro Requisição a api Cálculo de juros")]
        [Xunit.TraitAttribute("FeatureTitle", "Realizar requisição a api")]
        [Xunit.TraitAttribute("Description", "erro Requisição a api Cálculo de juros")]
        public virtual void ErroRequisicaoAApiCalculoDeJuros()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("erro Requisição a api Cálculo de juros", ((string[])(null)));
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("que realizo a requisição a api", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "quantidadeInicial",
                        "mes"});
            table2.AddRow(new string[] {
                        "100",
                        "0"});
#line 16
 testRunner.And("informo a quantidade inicial e a quantidade de meses", ((string)(null)), table2, "E ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "status",
                        "erro"});
            table3.AddRow(new string[] {
                        "404",
                        "dados incorretos"});
#line 19
 testRunner.Then("recebo recebo que a requisição foi inválida", ((string)(null)), table3, "Então ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.2.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                RealizarRequisicaoAApiFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                RealizarRequisicaoAApiFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
